from setuptools import setup

setup(
    name='m2dk.udm',
    version='v0.1',
    packages=['venv.lib.python2.7.distutils', 'venv.lib.python2.7.encodings', 'venv.lib.python2.7.site-packages.pip',
              'venv.lib.python2.7.site-packages.pip.req', 'venv.lib.python2.7.site-packages.pip.vcs',
              'venv.lib.python2.7.site-packages.pip.utils', 'venv.lib.python2.7.site-packages.pip.compat',
              'venv.lib.python2.7.site-packages.pip.models', 'venv.lib.python2.7.site-packages.pip._vendor',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python2.7.site-packages.pip._vendor.colorama',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python2.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python2.7.site-packages.pip._vendor.progress',
              'venv.lib.python2.7.site-packages.pip._vendor.requests',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.chardet',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.pip._vendor.packaging',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python2.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python2.7.site-packages.pip.commands', 'venv.lib.python2.7.site-packages.pip.operations',
              'venv.lib.python2.7.site-packages.zmq', 'venv.lib.python2.7.site-packages.zmq.log',
              'venv.lib.python2.7.site-packages.zmq.ssh', 'venv.lib.python2.7.site-packages.zmq.auth',
              'venv.lib.python2.7.site-packages.zmq.green', 'venv.lib.python2.7.site-packages.zmq.green.eventloop',
              'venv.lib.python2.7.site-packages.zmq.sugar', 'venv.lib.python2.7.site-packages.zmq.tests',
              'venv.lib.python2.7.site-packages.zmq.utils', 'venv.lib.python2.7.site-packages.zmq.backend',
              'venv.lib.python2.7.site-packages.zmq.backend.cffi',
              'venv.lib.python2.7.site-packages.zmq.backend.cython', 'venv.lib.python2.7.site-packages.zmq.devices',
              'venv.lib.python2.7.site-packages.zmq.eventloop',
              'venv.lib.python2.7.site-packages.zmq.eventloop.minitornado',
              'venv.lib.python2.7.site-packages.zmq.eventloop.minitornado.platform',
              'venv.lib.python2.7.site-packages.enum', 'venv.lib.python2.7.site-packages.pytz',
              'venv.lib.python2.7.site-packages.numpy', 'venv.lib.python2.7.site-packages.numpy.ma',
              'venv.lib.python2.7.site-packages.numpy.ma.tests', 'venv.lib.python2.7.site-packages.numpy.doc',
              'venv.lib.python2.7.site-packages.numpy.fft', 'venv.lib.python2.7.site-packages.numpy.fft.tests',
              'venv.lib.python2.7.site-packages.numpy.lib', 'venv.lib.python2.7.site-packages.numpy.lib.tests',
              'venv.lib.python2.7.site-packages.numpy.core', 'venv.lib.python2.7.site-packages.numpy.core.tests',
              'venv.lib.python2.7.site-packages.numpy.f2py', 'venv.lib.python2.7.site-packages.numpy.f2py.tests',
              'venv.lib.python2.7.site-packages.numpy.tests', 'venv.lib.python2.7.site-packages.numpy.compat',
              'venv.lib.python2.7.site-packages.numpy.linalg', 'venv.lib.python2.7.site-packages.numpy.linalg.tests',
              'venv.lib.python2.7.site-packages.numpy.random', 'venv.lib.python2.7.site-packages.numpy.random.tests',
              'venv.lib.python2.7.site-packages.numpy.testing', 'venv.lib.python2.7.site-packages.numpy.testing.tests',
              'venv.lib.python2.7.site-packages.numpy.testing.nose_tools',
              'venv.lib.python2.7.site-packages.numpy.distutils',
              'venv.lib.python2.7.site-packages.numpy.distutils.tests',
              'venv.lib.python2.7.site-packages.numpy.distutils.command',
              'venv.lib.python2.7.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python2.7.site-packages.numpy.matrixlib',
              'venv.lib.python2.7.site-packages.numpy.matrixlib.tests',
              'venv.lib.python2.7.site-packages.numpy.polynomial',
              'venv.lib.python2.7.site-packages.numpy.polynomial.tests', 'venv.lib.python2.7.site-packages.wheel',
              'venv.lib.python2.7.site-packages.wheel.tool', 'venv.lib.python2.7.site-packages.wheel.signatures',
              'venv.lib.python2.7.site-packages.bleach', 'venv.lib.python2.7.site-packages.jinja2',
              'venv.lib.python2.7.site-packages.pandas', 'venv.lib.python2.7.site-packages.pandas.io',
              'venv.lib.python2.7.site-packages.pandas.io.sas', 'venv.lib.python2.7.site-packages.pandas.io.json',
              'venv.lib.python2.7.site-packages.pandas.io.formats',
              'venv.lib.python2.7.site-packages.pandas.io.msgpack',
              'venv.lib.python2.7.site-packages.pandas.io.clipboard', 'venv.lib.python2.7.site-packages.pandas.api',
              'venv.lib.python2.7.site-packages.pandas.api.types', 'venv.lib.python2.7.site-packages.pandas.core',
              'venv.lib.python2.7.site-packages.pandas.core.util', 'venv.lib.python2.7.site-packages.pandas.core.tools',
              'venv.lib.python2.7.site-packages.pandas.core.dtypes',
              'venv.lib.python2.7.site-packages.pandas.core.sparse',
              'venv.lib.python2.7.site-packages.pandas.core.indexes',
              'venv.lib.python2.7.site-packages.pandas.core.reshape',
              'venv.lib.python2.7.site-packages.pandas.core.computation',
              'venv.lib.python2.7.site-packages.pandas.util', 'venv.lib.python2.7.site-packages.pandas._libs',
              'venv.lib.python2.7.site-packages.pandas._libs.tslibs', 'venv.lib.python2.7.site-packages.pandas.stats',
              'venv.lib.python2.7.site-packages.pandas.tests', 'venv.lib.python2.7.site-packages.pandas.tests.io',
              'venv.lib.python2.7.site-packages.pandas.tests.io.sas',
              'venv.lib.python2.7.site-packages.pandas.tests.io.json',
              'venv.lib.python2.7.site-packages.pandas.tests.io.parser',
              'venv.lib.python2.7.site-packages.pandas.tests.io.formats',
              'venv.lib.python2.7.site-packages.pandas.tests.io.msgpack',
              'venv.lib.python2.7.site-packages.pandas.tests.api', 'venv.lib.python2.7.site-packages.pandas.tests.util',
              'venv.lib.python2.7.site-packages.pandas.tests.frame',
              'venv.lib.python2.7.site-packages.pandas.tests.tools',
              'venv.lib.python2.7.site-packages.pandas.tests.dtypes',
              'venv.lib.python2.7.site-packages.pandas.tests.scalar',
              'venv.lib.python2.7.site-packages.pandas.tests.series',
              'venv.lib.python2.7.site-packages.pandas.tests.sparse',
              'venv.lib.python2.7.site-packages.pandas.tests.groupby',
              'venv.lib.python2.7.site-packages.pandas.tests.indexes',
              'venv.lib.python2.7.site-packages.pandas.tests.indexes.period',
              'venv.lib.python2.7.site-packages.pandas.tests.indexes.datetimes',
              'venv.lib.python2.7.site-packages.pandas.tests.indexes.timedeltas',
              'venv.lib.python2.7.site-packages.pandas.tests.reshape',
              'venv.lib.python2.7.site-packages.pandas.tests.tseries',
              'venv.lib.python2.7.site-packages.pandas.tests.indexing',
              'venv.lib.python2.7.site-packages.pandas.tests.plotting',
              'venv.lib.python2.7.site-packages.pandas.tests.internals',
              'venv.lib.python2.7.site-packages.pandas.tests.computation',
              'venv.lib.python2.7.site-packages.pandas.tools', 'venv.lib.python2.7.site-packages.pandas.types',
              'venv.lib.python2.7.site-packages.pandas.compat', 'venv.lib.python2.7.site-packages.pandas.compat.numpy',
              'venv.lib.python2.7.site-packages.pandas.errors', 'venv.lib.python2.7.site-packages.pandas.formats',
              'venv.lib.python2.7.site-packages.pandas.tseries', 'venv.lib.python2.7.site-packages.pandas.plotting',
              'venv.lib.python2.7.site-packages.pandas.computation', 'venv.lib.python2.7.site-packages.IPython',
              'venv.lib.python2.7.site-packages.IPython.lib', 'venv.lib.python2.7.site-packages.IPython.lib.tests',
              'venv.lib.python2.7.site-packages.IPython.core', 'venv.lib.python2.7.site-packages.IPython.core.tests',
              'venv.lib.python2.7.site-packages.IPython.core.magics', 'venv.lib.python2.7.site-packages.IPython.utils',
              'venv.lib.python2.7.site-packages.IPython.utils.tests', 'venv.lib.python2.7.site-packages.IPython.kernel',
              'venv.lib.python2.7.site-packages.IPython.testing',
              'venv.lib.python2.7.site-packages.IPython.testing.tests',
              'venv.lib.python2.7.site-packages.IPython.testing.plugin',
              'venv.lib.python2.7.site-packages.IPython.external',
              'venv.lib.python2.7.site-packages.IPython.external.decorators',
              'venv.lib.python2.7.site-packages.IPython.terminal',
              'venv.lib.python2.7.site-packages.IPython.terminal.tests',
              'venv.lib.python2.7.site-packages.IPython.terminal.pt_inputhooks',
              'venv.lib.python2.7.site-packages.IPython.sphinxext',
              'venv.lib.python2.7.site-packages.IPython.extensions',
              'venv.lib.python2.7.site-packages.IPython.extensions.tests', 'venv.lib.python2.7.site-packages.certifi',
              'venv.lib.python2.7.site-packages.pexpect', 'venv.lib.python2.7.site-packages.tornado',
              'venv.lib.python2.7.site-packages.tornado.test', 'venv.lib.python2.7.site-packages.tornado.platform',
              'venv.lib.python2.7.site-packages.wcwidth', 'venv.lib.python2.7.site-packages.wcwidth.tests',
              'venv.lib.python2.7.site-packages.dateutil', 'venv.lib.python2.7.site-packages.dateutil.tz',
              'venv.lib.python2.7.site-packages.dateutil.zoneinfo', 'venv.lib.python2.7.site-packages.html5lib',
              'venv.lib.python2.7.site-packages.html5lib._trie', 'venv.lib.python2.7.site-packages.html5lib.filters',
              'venv.lib.python2.7.site-packages.html5lib.treewalkers',
              'venv.lib.python2.7.site-packages.html5lib.treeadapters',
              'venv.lib.python2.7.site-packages.html5lib.treebuilders', 'venv.lib.python2.7.site-packages.nbformat',
              'venv.lib.python2.7.site-packages.nbformat.v1', 'venv.lib.python2.7.site-packages.nbformat.v1.tests',
              'venv.lib.python2.7.site-packages.nbformat.v2', 'venv.lib.python2.7.site-packages.nbformat.v2.tests',
              'venv.lib.python2.7.site-packages.nbformat.v3', 'venv.lib.python2.7.site-packages.nbformat.v3.tests',
              'venv.lib.python2.7.site-packages.nbformat.v4', 'venv.lib.python2.7.site-packages.nbformat.v4.tests',
              'venv.lib.python2.7.site-packages.nbformat.tests', 'venv.lib.python2.7.site-packages.networkx',
              'venv.lib.python2.7.site-packages.networkx.tests', 'venv.lib.python2.7.site-packages.networkx.utils',
              'venv.lib.python2.7.site-packages.networkx.linalg', 'venv.lib.python2.7.site-packages.networkx.classes',
              'venv.lib.python2.7.site-packages.networkx.drawing', 'venv.lib.python2.7.site-packages.networkx.testing',
              'venv.lib.python2.7.site-packages.networkx.readwrite',
              'venv.lib.python2.7.site-packages.networkx.readwrite.json_graph',
              'venv.lib.python2.7.site-packages.networkx.algorithms',
              'venv.lib.python2.7.site-packages.networkx.algorithms.flow',
              'venv.lib.python2.7.site-packages.networkx.algorithms.tree',
              'venv.lib.python2.7.site-packages.networkx.algorithms.coloring',
              'venv.lib.python2.7.site-packages.networkx.algorithms.bipartite',
              'venv.lib.python2.7.site-packages.networkx.algorithms.community',
              'venv.lib.python2.7.site-packages.networkx.algorithms.operators',
              'venv.lib.python2.7.site-packages.networkx.algorithms.traversal',
              'venv.lib.python2.7.site-packages.networkx.algorithms.centrality',
              'venv.lib.python2.7.site-packages.networkx.algorithms.components',
              'venv.lib.python2.7.site-packages.networkx.algorithms.isomorphism',
              'venv.lib.python2.7.site-packages.networkx.algorithms.connectivity',
              'venv.lib.python2.7.site-packages.networkx.algorithms.approximation',
              'venv.lib.python2.7.site-packages.networkx.algorithms.assortativity',
              'venv.lib.python2.7.site-packages.networkx.algorithms.link_analysis',
              'venv.lib.python2.7.site-packages.networkx.algorithms.shortest_paths',
              'venv.lib.python2.7.site-packages.networkx.generators', 'venv.lib.python2.7.site-packages.notebook',
              'venv.lib.python2.7.site-packages.notebook.auth', 'venv.lib.python2.7.site-packages.notebook.auth.tests',
              'venv.lib.python2.7.site-packages.notebook.base', 'venv.lib.python2.7.site-packages.notebook.edit',
              'venv.lib.python2.7.site-packages.notebook.i18n', 'venv.lib.python2.7.site-packages.notebook.tree',
              'venv.lib.python2.7.site-packages.notebook.tree.tests', 'venv.lib.python2.7.site-packages.notebook.view',
              'venv.lib.python2.7.site-packages.notebook.files', 'venv.lib.python2.7.site-packages.notebook.tests',
              'venv.lib.python2.7.site-packages.notebook.bundler',
              'venv.lib.python2.7.site-packages.notebook.bundler.tests',
              'venv.lib.python2.7.site-packages.notebook.notebook',
              'venv.lib.python2.7.site-packages.notebook.services',
              'venv.lib.python2.7.site-packages.notebook.services.api',
              'venv.lib.python2.7.site-packages.notebook.services.api.tests',
              'venv.lib.python2.7.site-packages.notebook.services.config',
              'venv.lib.python2.7.site-packages.notebook.services.config.tests',
              'venv.lib.python2.7.site-packages.notebook.services.kernels',
              'venv.lib.python2.7.site-packages.notebook.services.kernels.tests',
              'venv.lib.python2.7.site-packages.notebook.services.contents',
              'venv.lib.python2.7.site-packages.notebook.services.contents.tests',
              'venv.lib.python2.7.site-packages.notebook.services.security',
              'venv.lib.python2.7.site-packages.notebook.services.sessions',
              'venv.lib.python2.7.site-packages.notebook.services.sessions.tests',
              'venv.lib.python2.7.site-packages.notebook.services.nbconvert',
              'venv.lib.python2.7.site-packages.notebook.services.nbconvert.tests',
              'venv.lib.python2.7.site-packages.notebook.services.kernelspecs',
              'venv.lib.python2.7.site-packages.notebook.services.kernelspecs.tests',
              'venv.lib.python2.7.site-packages.notebook.terminal',
              'venv.lib.python2.7.site-packages.notebook.nbconvert',
              'venv.lib.python2.7.site-packages.notebook.nbconvert.tests',
              'venv.lib.python2.7.site-packages.notebook.kernelspecs', 'venv.lib.python2.7.site-packages.pygments',
              'venv.lib.python2.7.site-packages.pygments.lexers', 'venv.lib.python2.7.site-packages.pygments.styles',
              'venv.lib.python2.7.site-packages.pygments.filters',
              'venv.lib.python2.7.site-packages.pygments.formatters', 'venv.lib.python2.7.site-packages.testpath',
              'venv.lib.python2.7.site-packages.backports', 'venv.lib.python2.7.site-packages.backports.configparser',
              'venv.lib.python2.7.site-packages.backports.shutil_get_terminal_size',
              'venv.lib.python2.7.site-packages.ipykernel', 'venv.lib.python2.7.site-packages.ipykernel.gui',
              'venv.lib.python2.7.site-packages.ipykernel.comm', 'venv.lib.python2.7.site-packages.ipykernel.pylab',
              'venv.lib.python2.7.site-packages.ipykernel.tests',
              'venv.lib.python2.7.site-packages.ipykernel.inprocess',
              'venv.lib.python2.7.site-packages.ipykernel.inprocess.tests',
              'venv.lib.python2.7.site-packages.nbconvert', 'venv.lib.python2.7.site-packages.nbconvert.tests',
              'venv.lib.python2.7.site-packages.nbconvert.utils',
              'venv.lib.python2.7.site-packages.nbconvert.utils.tests',
              'venv.lib.python2.7.site-packages.nbconvert.filters',
              'venv.lib.python2.7.site-packages.nbconvert.filters.tests',
              'venv.lib.python2.7.site-packages.nbconvert.writers',
              'venv.lib.python2.7.site-packages.nbconvert.writers.tests',
              'venv.lib.python2.7.site-packages.nbconvert.exporters',
              'venv.lib.python2.7.site-packages.nbconvert.exporters.tests',
              'venv.lib.python2.7.site-packages.nbconvert.resources',
              'venv.lib.python2.7.site-packages.nbconvert.preprocessors',
              'venv.lib.python2.7.site-packages.nbconvert.preprocessors.tests',
              'venv.lib.python2.7.site-packages.nbconvert.postprocessors',
              'venv.lib.python2.7.site-packages.nbconvert.postprocessors.tests',
              'venv.lib.python2.7.site-packages.qtconsole', 'venv.lib.python2.7.site-packages.qtconsole.tests',
              'venv.lib.python2.7.site-packages.terminado', 'venv.lib.python2.7.site-packages.terminado.tests',
              'venv.lib.python2.7.site-packages.traitlets', 'venv.lib.python2.7.site-packages.traitlets.tests',
              'venv.lib.python2.7.site-packages.traitlets.utils',
              'venv.lib.python2.7.site-packages.traitlets.utils.tests',
              'venv.lib.python2.7.site-packages.traitlets.config',
              'venv.lib.python2.7.site-packages.traitlets.config.tests', 'venv.lib.python2.7.site-packages.ipywidgets',
              'venv.lib.python2.7.site-packages.ipywidgets.tests',
              'venv.lib.python2.7.site-packages.ipywidgets.widgets',
              'venv.lib.python2.7.site-packages.ipywidgets.widgets.tests',
              'venv.lib.python2.7.site-packages.jsonschema', 'venv.lib.python2.7.site-packages.jsonschema.tests',
              'venv.lib.python2.7.site-packages.markupsafe', 'venv.lib.python2.7.site-packages.matplotlib',
              'venv.lib.python2.7.site-packages.matplotlib.tri', 'venv.lib.python2.7.site-packages.matplotlib.axes',
              'venv.lib.python2.7.site-packages.matplotlib.cbook', 'venv.lib.python2.7.site-packages.matplotlib.style',
              'venv.lib.python2.7.site-packages.matplotlib.tests', 'venv.lib.python2.7.site-packages.matplotlib.compat',
              'venv.lib.python2.7.site-packages.matplotlib.testing',
              'venv.lib.python2.7.site-packages.matplotlib.testing._nose',
              'venv.lib.python2.7.site-packages.matplotlib.testing._nose.plugins',
              'venv.lib.python2.7.site-packages.matplotlib.testing.jpl_units',
              'venv.lib.python2.7.site-packages.matplotlib.backends',
              'venv.lib.python2.7.site-packages.matplotlib.backends.qt_editor',
              'venv.lib.python2.7.site-packages.matplotlib.sphinxext',
              'venv.lib.python2.7.site-packages.matplotlib.sphinxext.tests',
              'venv.lib.python2.7.site-packages.matplotlib.projections', 'venv.lib.python2.7.site-packages.ptyprocess',
              'venv.lib.python2.7.site-packages.send2trash', 'venv.lib.python2.7.site-packages.setuptools',
              'venv.lib.python2.7.site-packages.setuptools.extern',
              'venv.lib.python2.7.site-packages.setuptools.command', 'venv.lib.python2.7.site-packages.functools32',
              'venv.lib.python2.7.site-packages.jupyter_core', 'venv.lib.python2.7.site-packages.jupyter_core.tests',
              'venv.lib.python2.7.site-packages.jupyter_core.utils',
              'venv.lib.python2.7.site-packages.mpl_toolkits.tests',
              'venv.lib.python2.7.site-packages.mpl_toolkits.mplot3d',
              'venv.lib.python2.7.site-packages.mpl_toolkits.axes_grid',
              'venv.lib.python2.7.site-packages.mpl_toolkits.axes_grid1',
              'venv.lib.python2.7.site-packages.mpl_toolkits.axisartist',
              'venv.lib.python2.7.site-packages.webencodings', 'venv.lib.python2.7.site-packages.pkg_resources',
              'venv.lib.python2.7.site-packages.pkg_resources.extern',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor.packaging',
              'venv.lib.python2.7.site-packages.jupyter_client',
              'venv.lib.python2.7.site-packages.jupyter_client.tests',
              'venv.lib.python2.7.site-packages.jupyter_client.ioloop',
              'venv.lib.python2.7.site-packages.jupyter_client.blocking',
              'venv.lib.python2.7.site-packages.prompt_toolkit',
              'venv.lib.python2.7.site-packages.prompt_toolkit.layout',
              'venv.lib.python2.7.site-packages.prompt_toolkit.styles',
              'venv.lib.python2.7.site-packages.prompt_toolkit.contrib',
              'venv.lib.python2.7.site-packages.prompt_toolkit.contrib.telnet',
              'venv.lib.python2.7.site-packages.prompt_toolkit.contrib.completers',
              'venv.lib.python2.7.site-packages.prompt_toolkit.contrib.validators',
              'venv.lib.python2.7.site-packages.prompt_toolkit.contrib.regular_languages',
              'venv.lib.python2.7.site-packages.prompt_toolkit.filters',
              'venv.lib.python2.7.site-packages.prompt_toolkit.terminal',
              'venv.lib.python2.7.site-packages.prompt_toolkit.clipboard',
              'venv.lib.python2.7.site-packages.prompt_toolkit.eventloop',
              'venv.lib.python2.7.site-packages.prompt_toolkit.key_binding',
              'venv.lib.python2.7.site-packages.prompt_toolkit.key_binding.bindings',
              'venv.lib.python2.7.site-packages.jupyter_console',
              'venv.lib.python2.7.site-packages.jupyter_console.tests',
              'venv.lib.python2.7.site-packages.ipython_genutils',
              'venv.lib.python2.7.site-packages.ipython_genutils.tests',
              'venv.lib.python2.7.site-packages.ipython_genutils.testing',
              'venv.lib.python2.7.site-packages.shutil_backports',
              'venv.lib.python2.7.site-packages.widgetsnbextension', 'venv.local.lib.python2.7.site-packages.pip',
              'venv.local.lib.python2.7.site-packages.pip.req', 'venv.local.lib.python2.7.site-packages.pip.vcs',
              'venv.local.lib.python2.7.site-packages.pip.utils', 'venv.local.lib.python2.7.site-packages.pip.compat',
              'venv.local.lib.python2.7.site-packages.pip.models', 'venv.local.lib.python2.7.site-packages.pip._vendor',
              'venv.local.lib.python2.7.site-packages.pip._vendor.distlib',
              'venv.local.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'venv.local.lib.python2.7.site-packages.pip._vendor.colorama',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.local.lib.python2.7.site-packages.pip._vendor.lockfile',
              'venv.local.lib.python2.7.site-packages.pip._vendor.progress',
              'venv.local.lib.python2.7.site-packages.pip._vendor.requests',
              'venv.local.lib.python2.7.site-packages.pip._vendor.requests.packages',
              'venv.local.lib.python2.7.site-packages.pip._vendor.requests.packages.chardet',
              'venv.local.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.local.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.local.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.local.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.local.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.local.lib.python2.7.site-packages.pip._vendor.packaging',
              'venv.local.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'venv.local.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.local.lib.python2.7.site-packages.pip._vendor.webencodings',
              'venv.local.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'venv.local.lib.python2.7.site-packages.pip.commands',
              'venv.local.lib.python2.7.site-packages.pip.operations', 'venv.local.lib.python2.7.site-packages.zmq',
              'venv.local.lib.python2.7.site-packages.zmq.log', 'venv.local.lib.python2.7.site-packages.zmq.ssh',
              'venv.local.lib.python2.7.site-packages.zmq.auth', 'venv.local.lib.python2.7.site-packages.zmq.green',
              'venv.local.lib.python2.7.site-packages.zmq.green.eventloop',
              'venv.local.lib.python2.7.site-packages.zmq.sugar', 'venv.local.lib.python2.7.site-packages.zmq.tests',
              'venv.local.lib.python2.7.site-packages.zmq.utils', 'venv.local.lib.python2.7.site-packages.zmq.backend',
              'venv.local.lib.python2.7.site-packages.zmq.backend.cffi',
              'venv.local.lib.python2.7.site-packages.zmq.backend.cython',
              'venv.local.lib.python2.7.site-packages.zmq.devices',
              'venv.local.lib.python2.7.site-packages.zmq.eventloop',
              'venv.local.lib.python2.7.site-packages.zmq.eventloop.minitornado',
              'venv.local.lib.python2.7.site-packages.zmq.eventloop.minitornado.platform',
              'venv.local.lib.python2.7.site-packages.enum', 'venv.local.lib.python2.7.site-packages.pytz',
              'venv.local.lib.python2.7.site-packages.numpy', 'venv.local.lib.python2.7.site-packages.numpy.ma',
              'venv.local.lib.python2.7.site-packages.numpy.ma.tests',
              'venv.local.lib.python2.7.site-packages.numpy.doc', 'venv.local.lib.python2.7.site-packages.numpy.fft',
              'venv.local.lib.python2.7.site-packages.numpy.fft.tests',
              'venv.local.lib.python2.7.site-packages.numpy.lib',
              'venv.local.lib.python2.7.site-packages.numpy.lib.tests',
              'venv.local.lib.python2.7.site-packages.numpy.core',
              'venv.local.lib.python2.7.site-packages.numpy.core.tests',
              'venv.local.lib.python2.7.site-packages.numpy.f2py',
              'venv.local.lib.python2.7.site-packages.numpy.f2py.tests',
              'venv.local.lib.python2.7.site-packages.numpy.tests',
              'venv.local.lib.python2.7.site-packages.numpy.compat',
              'venv.local.lib.python2.7.site-packages.numpy.linalg',
              'venv.local.lib.python2.7.site-packages.numpy.linalg.tests',
              'venv.local.lib.python2.7.site-packages.numpy.random',
              'venv.local.lib.python2.7.site-packages.numpy.random.tests',
              'venv.local.lib.python2.7.site-packages.numpy.testing',
              'venv.local.lib.python2.7.site-packages.numpy.testing.tests',
              'venv.local.lib.python2.7.site-packages.numpy.testing.nose_tools',
              'venv.local.lib.python2.7.site-packages.numpy.distutils',
              'venv.local.lib.python2.7.site-packages.numpy.distutils.tests',
              'venv.local.lib.python2.7.site-packages.numpy.distutils.command',
              'venv.local.lib.python2.7.site-packages.numpy.distutils.fcompiler',
              'venv.local.lib.python2.7.site-packages.numpy.matrixlib',
              'venv.local.lib.python2.7.site-packages.numpy.matrixlib.tests',
              'venv.local.lib.python2.7.site-packages.numpy.polynomial',
              'venv.local.lib.python2.7.site-packages.numpy.polynomial.tests',
              'venv.local.lib.python2.7.site-packages.wheel', 'venv.local.lib.python2.7.site-packages.wheel.tool',
              'venv.local.lib.python2.7.site-packages.wheel.signatures',
              'venv.local.lib.python2.7.site-packages.bleach', 'venv.local.lib.python2.7.site-packages.jinja2',
              'venv.local.lib.python2.7.site-packages.pandas', 'venv.local.lib.python2.7.site-packages.pandas.io',
              'venv.local.lib.python2.7.site-packages.pandas.io.sas',
              'venv.local.lib.python2.7.site-packages.pandas.io.json',
              'venv.local.lib.python2.7.site-packages.pandas.io.formats',
              'venv.local.lib.python2.7.site-packages.pandas.io.msgpack',
              'venv.local.lib.python2.7.site-packages.pandas.io.clipboard',
              'venv.local.lib.python2.7.site-packages.pandas.api',
              'venv.local.lib.python2.7.site-packages.pandas.api.types',
              'venv.local.lib.python2.7.site-packages.pandas.core',
              'venv.local.lib.python2.7.site-packages.pandas.core.util',
              'venv.local.lib.python2.7.site-packages.pandas.core.tools',
              'venv.local.lib.python2.7.site-packages.pandas.core.dtypes',
              'venv.local.lib.python2.7.site-packages.pandas.core.sparse',
              'venv.local.lib.python2.7.site-packages.pandas.core.indexes',
              'venv.local.lib.python2.7.site-packages.pandas.core.reshape',
              'venv.local.lib.python2.7.site-packages.pandas.core.computation',
              'venv.local.lib.python2.7.site-packages.pandas.util',
              'venv.local.lib.python2.7.site-packages.pandas._libs',
              'venv.local.lib.python2.7.site-packages.pandas._libs.tslibs',
              'venv.local.lib.python2.7.site-packages.pandas.stats',
              'venv.local.lib.python2.7.site-packages.pandas.tests',
              'venv.local.lib.python2.7.site-packages.pandas.tests.io',
              'venv.local.lib.python2.7.site-packages.pandas.tests.io.sas',
              'venv.local.lib.python2.7.site-packages.pandas.tests.io.json',
              'venv.local.lib.python2.7.site-packages.pandas.tests.io.parser',
              'venv.local.lib.python2.7.site-packages.pandas.tests.io.formats',
              'venv.local.lib.python2.7.site-packages.pandas.tests.io.msgpack',
              'venv.local.lib.python2.7.site-packages.pandas.tests.api',
              'venv.local.lib.python2.7.site-packages.pandas.tests.util',
              'venv.local.lib.python2.7.site-packages.pandas.tests.frame',
              'venv.local.lib.python2.7.site-packages.pandas.tests.tools',
              'venv.local.lib.python2.7.site-packages.pandas.tests.dtypes',
              'venv.local.lib.python2.7.site-packages.pandas.tests.scalar',
              'venv.local.lib.python2.7.site-packages.pandas.tests.series',
              'venv.local.lib.python2.7.site-packages.pandas.tests.sparse',
              'venv.local.lib.python2.7.site-packages.pandas.tests.groupby',
              'venv.local.lib.python2.7.site-packages.pandas.tests.indexes',
              'venv.local.lib.python2.7.site-packages.pandas.tests.indexes.period',
              'venv.local.lib.python2.7.site-packages.pandas.tests.indexes.datetimes',
              'venv.local.lib.python2.7.site-packages.pandas.tests.indexes.timedeltas',
              'venv.local.lib.python2.7.site-packages.pandas.tests.reshape',
              'venv.local.lib.python2.7.site-packages.pandas.tests.tseries',
              'venv.local.lib.python2.7.site-packages.pandas.tests.indexing',
              'venv.local.lib.python2.7.site-packages.pandas.tests.plotting',
              'venv.local.lib.python2.7.site-packages.pandas.tests.internals',
              'venv.local.lib.python2.7.site-packages.pandas.tests.computation',
              'venv.local.lib.python2.7.site-packages.pandas.tools',
              'venv.local.lib.python2.7.site-packages.pandas.types',
              'venv.local.lib.python2.7.site-packages.pandas.compat',
              'venv.local.lib.python2.7.site-packages.pandas.compat.numpy',
              'venv.local.lib.python2.7.site-packages.pandas.errors',
              'venv.local.lib.python2.7.site-packages.pandas.formats',
              'venv.local.lib.python2.7.site-packages.pandas.tseries',
              'venv.local.lib.python2.7.site-packages.pandas.plotting',
              'venv.local.lib.python2.7.site-packages.pandas.computation',
              'venv.local.lib.python2.7.site-packages.IPython', 'venv.local.lib.python2.7.site-packages.IPython.lib',
              'venv.local.lib.python2.7.site-packages.IPython.lib.tests',
              'venv.local.lib.python2.7.site-packages.IPython.core',
              'venv.local.lib.python2.7.site-packages.IPython.core.tests',
              'venv.local.lib.python2.7.site-packages.IPython.core.magics',
              'venv.local.lib.python2.7.site-packages.IPython.utils',
              'venv.local.lib.python2.7.site-packages.IPython.utils.tests',
              'venv.local.lib.python2.7.site-packages.IPython.kernel',
              'venv.local.lib.python2.7.site-packages.IPython.testing',
              'venv.local.lib.python2.7.site-packages.IPython.testing.tests',
              'venv.local.lib.python2.7.site-packages.IPython.testing.plugin',
              'venv.local.lib.python2.7.site-packages.IPython.external',
              'venv.local.lib.python2.7.site-packages.IPython.external.decorators',
              'venv.local.lib.python2.7.site-packages.IPython.terminal',
              'venv.local.lib.python2.7.site-packages.IPython.terminal.tests',
              'venv.local.lib.python2.7.site-packages.IPython.terminal.pt_inputhooks',
              'venv.local.lib.python2.7.site-packages.IPython.sphinxext',
              'venv.local.lib.python2.7.site-packages.IPython.extensions',
              'venv.local.lib.python2.7.site-packages.IPython.extensions.tests',
              'venv.local.lib.python2.7.site-packages.certifi', 'venv.local.lib.python2.7.site-packages.pexpect',
              'venv.local.lib.python2.7.site-packages.tornado', 'venv.local.lib.python2.7.site-packages.tornado.test',
              'venv.local.lib.python2.7.site-packages.tornado.platform',
              'venv.local.lib.python2.7.site-packages.wcwidth', 'venv.local.lib.python2.7.site-packages.wcwidth.tests',
              'venv.local.lib.python2.7.site-packages.dateutil', 'venv.local.lib.python2.7.site-packages.dateutil.tz',
              'venv.local.lib.python2.7.site-packages.dateutil.zoneinfo',
              'venv.local.lib.python2.7.site-packages.html5lib',
              'venv.local.lib.python2.7.site-packages.html5lib._trie',
              'venv.local.lib.python2.7.site-packages.html5lib.filters',
              'venv.local.lib.python2.7.site-packages.html5lib.treewalkers',
              'venv.local.lib.python2.7.site-packages.html5lib.treeadapters',
              'venv.local.lib.python2.7.site-packages.html5lib.treebuilders',
              'venv.local.lib.python2.7.site-packages.nbformat', 'venv.local.lib.python2.7.site-packages.nbformat.v1',
              'venv.local.lib.python2.7.site-packages.nbformat.v1.tests',
              'venv.local.lib.python2.7.site-packages.nbformat.v2',
              'venv.local.lib.python2.7.site-packages.nbformat.v2.tests',
              'venv.local.lib.python2.7.site-packages.nbformat.v3',
              'venv.local.lib.python2.7.site-packages.nbformat.v3.tests',
              'venv.local.lib.python2.7.site-packages.nbformat.v4',
              'venv.local.lib.python2.7.site-packages.nbformat.v4.tests',
              'venv.local.lib.python2.7.site-packages.nbformat.tests',
              'venv.local.lib.python2.7.site-packages.networkx',
              'venv.local.lib.python2.7.site-packages.networkx.tests',
              'venv.local.lib.python2.7.site-packages.networkx.utils',
              'venv.local.lib.python2.7.site-packages.networkx.linalg',
              'venv.local.lib.python2.7.site-packages.networkx.classes',
              'venv.local.lib.python2.7.site-packages.networkx.drawing',
              'venv.local.lib.python2.7.site-packages.networkx.testing',
              'venv.local.lib.python2.7.site-packages.networkx.readwrite',
              'venv.local.lib.python2.7.site-packages.networkx.readwrite.json_graph',
              'venv.local.lib.python2.7.site-packages.networkx.algorithms',
              'venv.local.lib.python2.7.site-packages.networkx.algorithms.flow',
              'venv.local.lib.python2.7.site-packages.networkx.algorithms.tree',
              'venv.local.lib.python2.7.site-packages.networkx.algorithms.coloring',
              'venv.local.lib.python2.7.site-packages.networkx.algorithms.bipartite',
              'venv.local.lib.python2.7.site-packages.networkx.algorithms.community',
              'venv.local.lib.python2.7.site-packages.networkx.algorithms.operators',
              'venv.local.lib.python2.7.site-packages.networkx.algorithms.traversal',
              'venv.local.lib.python2.7.site-packages.networkx.algorithms.centrality',
              'venv.local.lib.python2.7.site-packages.networkx.algorithms.components',
              'venv.local.lib.python2.7.site-packages.networkx.algorithms.isomorphism',
              'venv.local.lib.python2.7.site-packages.networkx.algorithms.connectivity',
              'venv.local.lib.python2.7.site-packages.networkx.algorithms.approximation',
              'venv.local.lib.python2.7.site-packages.networkx.algorithms.assortativity',
              'venv.local.lib.python2.7.site-packages.networkx.algorithms.link_analysis',
              'venv.local.lib.python2.7.site-packages.networkx.algorithms.shortest_paths',
              'venv.local.lib.python2.7.site-packages.networkx.generators',
              'venv.local.lib.python2.7.site-packages.notebook', 'venv.local.lib.python2.7.site-packages.notebook.auth',
              'venv.local.lib.python2.7.site-packages.notebook.auth.tests',
              'venv.local.lib.python2.7.site-packages.notebook.base',
              'venv.local.lib.python2.7.site-packages.notebook.edit',
              'venv.local.lib.python2.7.site-packages.notebook.i18n',
              'venv.local.lib.python2.7.site-packages.notebook.tree',
              'venv.local.lib.python2.7.site-packages.notebook.tree.tests',
              'venv.local.lib.python2.7.site-packages.notebook.view',
              'venv.local.lib.python2.7.site-packages.notebook.files',
              'venv.local.lib.python2.7.site-packages.notebook.tests',
              'venv.local.lib.python2.7.site-packages.notebook.bundler',
              'venv.local.lib.python2.7.site-packages.notebook.bundler.tests',
              'venv.local.lib.python2.7.site-packages.notebook.notebook',
              'venv.local.lib.python2.7.site-packages.notebook.services',
              'venv.local.lib.python2.7.site-packages.notebook.services.api',
              'venv.local.lib.python2.7.site-packages.notebook.services.api.tests',
              'venv.local.lib.python2.7.site-packages.notebook.services.config',
              'venv.local.lib.python2.7.site-packages.notebook.services.config.tests',
              'venv.local.lib.python2.7.site-packages.notebook.services.kernels',
              'venv.local.lib.python2.7.site-packages.notebook.services.kernels.tests',
              'venv.local.lib.python2.7.site-packages.notebook.services.contents',
              'venv.local.lib.python2.7.site-packages.notebook.services.contents.tests',
              'venv.local.lib.python2.7.site-packages.notebook.services.security',
              'venv.local.lib.python2.7.site-packages.notebook.services.sessions',
              'venv.local.lib.python2.7.site-packages.notebook.services.sessions.tests',
              'venv.local.lib.python2.7.site-packages.notebook.services.nbconvert',
              'venv.local.lib.python2.7.site-packages.notebook.services.nbconvert.tests',
              'venv.local.lib.python2.7.site-packages.notebook.services.kernelspecs',
              'venv.local.lib.python2.7.site-packages.notebook.services.kernelspecs.tests',
              'venv.local.lib.python2.7.site-packages.notebook.terminal',
              'venv.local.lib.python2.7.site-packages.notebook.nbconvert',
              'venv.local.lib.python2.7.site-packages.notebook.nbconvert.tests',
              'venv.local.lib.python2.7.site-packages.notebook.kernelspecs',
              'venv.local.lib.python2.7.site-packages.pygments',
              'venv.local.lib.python2.7.site-packages.pygments.lexers',
              'venv.local.lib.python2.7.site-packages.pygments.styles',
              'venv.local.lib.python2.7.site-packages.pygments.filters',
              'venv.local.lib.python2.7.site-packages.pygments.formatters',
              'venv.local.lib.python2.7.site-packages.testpath', 'venv.local.lib.python2.7.site-packages.backports',
              'venv.local.lib.python2.7.site-packages.backports.configparser',
              'venv.local.lib.python2.7.site-packages.backports.shutil_get_terminal_size',
              'venv.local.lib.python2.7.site-packages.ipykernel',
              'venv.local.lib.python2.7.site-packages.ipykernel.gui',
              'venv.local.lib.python2.7.site-packages.ipykernel.comm',
              'venv.local.lib.python2.7.site-packages.ipykernel.pylab',
              'venv.local.lib.python2.7.site-packages.ipykernel.tests',
              'venv.local.lib.python2.7.site-packages.ipykernel.inprocess',
              'venv.local.lib.python2.7.site-packages.ipykernel.inprocess.tests',
              'venv.local.lib.python2.7.site-packages.nbconvert',
              'venv.local.lib.python2.7.site-packages.nbconvert.tests',
              'venv.local.lib.python2.7.site-packages.nbconvert.utils',
              'venv.local.lib.python2.7.site-packages.nbconvert.utils.tests',
              'venv.local.lib.python2.7.site-packages.nbconvert.filters',
              'venv.local.lib.python2.7.site-packages.nbconvert.filters.tests',
              'venv.local.lib.python2.7.site-packages.nbconvert.writers',
              'venv.local.lib.python2.7.site-packages.nbconvert.writers.tests',
              'venv.local.lib.python2.7.site-packages.nbconvert.exporters',
              'venv.local.lib.python2.7.site-packages.nbconvert.exporters.tests',
              'venv.local.lib.python2.7.site-packages.nbconvert.resources',
              'venv.local.lib.python2.7.site-packages.nbconvert.preprocessors',
              'venv.local.lib.python2.7.site-packages.nbconvert.preprocessors.tests',
              'venv.local.lib.python2.7.site-packages.nbconvert.postprocessors',
              'venv.local.lib.python2.7.site-packages.nbconvert.postprocessors.tests',
              'venv.local.lib.python2.7.site-packages.qtconsole',
              'venv.local.lib.python2.7.site-packages.qtconsole.tests',
              'venv.local.lib.python2.7.site-packages.terminado',
              'venv.local.lib.python2.7.site-packages.terminado.tests',
              'venv.local.lib.python2.7.site-packages.traitlets',
              'venv.local.lib.python2.7.site-packages.traitlets.tests',
              'venv.local.lib.python2.7.site-packages.traitlets.utils',
              'venv.local.lib.python2.7.site-packages.traitlets.utils.tests',
              'venv.local.lib.python2.7.site-packages.traitlets.config',
              'venv.local.lib.python2.7.site-packages.traitlets.config.tests',
              'venv.local.lib.python2.7.site-packages.ipywidgets',
              'venv.local.lib.python2.7.site-packages.ipywidgets.tests',
              'venv.local.lib.python2.7.site-packages.ipywidgets.widgets',
              'venv.local.lib.python2.7.site-packages.ipywidgets.widgets.tests',
              'venv.local.lib.python2.7.site-packages.jsonschema',
              'venv.local.lib.python2.7.site-packages.jsonschema.tests',
              'venv.local.lib.python2.7.site-packages.markupsafe', 'venv.local.lib.python2.7.site-packages.matplotlib',
              'venv.local.lib.python2.7.site-packages.matplotlib.tri',
              'venv.local.lib.python2.7.site-packages.matplotlib.axes',
              'venv.local.lib.python2.7.site-packages.matplotlib.cbook',
              'venv.local.lib.python2.7.site-packages.matplotlib.style',
              'venv.local.lib.python2.7.site-packages.matplotlib.tests',
              'venv.local.lib.python2.7.site-packages.matplotlib.compat',
              'venv.local.lib.python2.7.site-packages.matplotlib.testing',
              'venv.local.lib.python2.7.site-packages.matplotlib.testing._nose',
              'venv.local.lib.python2.7.site-packages.matplotlib.testing._nose.plugins',
              'venv.local.lib.python2.7.site-packages.matplotlib.testing.jpl_units',
              'venv.local.lib.python2.7.site-packages.matplotlib.backends',
              'venv.local.lib.python2.7.site-packages.matplotlib.backends.qt_editor',
              'venv.local.lib.python2.7.site-packages.matplotlib.sphinxext',
              'venv.local.lib.python2.7.site-packages.matplotlib.sphinxext.tests',
              'venv.local.lib.python2.7.site-packages.matplotlib.projections',
              'venv.local.lib.python2.7.site-packages.ptyprocess', 'venv.local.lib.python2.7.site-packages.send2trash',
              'venv.local.lib.python2.7.site-packages.setuptools',
              'venv.local.lib.python2.7.site-packages.setuptools.extern',
              'venv.local.lib.python2.7.site-packages.setuptools.command',
              'venv.local.lib.python2.7.site-packages.functools32',
              'venv.local.lib.python2.7.site-packages.jupyter_core',
              'venv.local.lib.python2.7.site-packages.jupyter_core.tests',
              'venv.local.lib.python2.7.site-packages.jupyter_core.utils',
              'venv.local.lib.python2.7.site-packages.mpl_toolkits.tests',
              'venv.local.lib.python2.7.site-packages.mpl_toolkits.mplot3d',
              'venv.local.lib.python2.7.site-packages.mpl_toolkits.axes_grid',
              'venv.local.lib.python2.7.site-packages.mpl_toolkits.axes_grid1',
              'venv.local.lib.python2.7.site-packages.mpl_toolkits.axisartist',
              'venv.local.lib.python2.7.site-packages.webencodings',
              'venv.local.lib.python2.7.site-packages.pkg_resources',
              'venv.local.lib.python2.7.site-packages.pkg_resources.extern',
              'venv.local.lib.python2.7.site-packages.pkg_resources._vendor',
              'venv.local.lib.python2.7.site-packages.pkg_resources._vendor.packaging',
              'venv.local.lib.python2.7.site-packages.jupyter_client',
              'venv.local.lib.python2.7.site-packages.jupyter_client.tests',
              'venv.local.lib.python2.7.site-packages.jupyter_client.ioloop',
              'venv.local.lib.python2.7.site-packages.jupyter_client.blocking',
              'venv.local.lib.python2.7.site-packages.prompt_toolkit',
              'venv.local.lib.python2.7.site-packages.prompt_toolkit.layout',
              'venv.local.lib.python2.7.site-packages.prompt_toolkit.styles',
              'venv.local.lib.python2.7.site-packages.prompt_toolkit.contrib',
              'venv.local.lib.python2.7.site-packages.prompt_toolkit.contrib.telnet',
              'venv.local.lib.python2.7.site-packages.prompt_toolkit.contrib.completers',
              'venv.local.lib.python2.7.site-packages.prompt_toolkit.contrib.validators',
              'venv.local.lib.python2.7.site-packages.prompt_toolkit.contrib.regular_languages',
              'venv.local.lib.python2.7.site-packages.prompt_toolkit.filters',
              'venv.local.lib.python2.7.site-packages.prompt_toolkit.terminal',
              'venv.local.lib.python2.7.site-packages.prompt_toolkit.clipboard',
              'venv.local.lib.python2.7.site-packages.prompt_toolkit.eventloop',
              'venv.local.lib.python2.7.site-packages.prompt_toolkit.key_binding',
              'venv.local.lib.python2.7.site-packages.prompt_toolkit.key_binding.bindings',
              'venv.local.lib.python2.7.site-packages.jupyter_console',
              'venv.local.lib.python2.7.site-packages.jupyter_console.tests',
              'venv.local.lib.python2.7.site-packages.ipython_genutils',
              'venv.local.lib.python2.7.site-packages.ipython_genutils.tests',
              'venv.local.lib.python2.7.site-packages.ipython_genutils.testing',
              'venv.local.lib.python2.7.site-packages.shutil_backports',
              'venv.local.lib.python2.7.site-packages.widgetsnbextension'],
    url='',
    license='MIT License',
    author='mkobbi',
    author_email='mahmoud.kobbi@hotmail.fr',
    description='This package permits the execution of all requirements of the Data Analysis Project'
)
